version: "3"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1221
      - N8N_SECURE_COOKIE=false
      - TZ=Europe/Moscow
    volumes:
      - ./n8n_data:/home/node/.n8n